title:              BBangi BlogğŸ—‚
email:              jinhyuk0103@gmail.com
description:        ë°©ì§„í˜ ê°œë°œ ê³µë¶€ ë¸”ë¡œê·¸
author:             Bangjinhyuk
baseurl:            ""
url:                "https://bangjinhyuk.github.io"

# Social Profiles
twitter_username:
github_username:    bangjinhyuk
facebook_username:  profile.php?id=100001548378047
instagram_username:  bbangi_98
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
